FROM nginx

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/indahhre/UAS-CC /tmp/repo
RUN ls -lah /tmp/repo
RUN cp -r /tmp/repo/Project-uas* /usr/share/nginx/html/

EXPOSE 80